### ISSUE TITLE
blox reset wifi

### ISSUE THREAD

**Issue by ehsan6sha** [functionland/fx-components#297]
Under re-connect to wifi in home screen, if the blox status is connected, it first calls a reset wifi api that sends a command to blox over libp2p to put it in hotspot mode first. After this step the app should go to connect to Hotspot

**Comment by ehsan6sha** [comment]
Added in rn-fula: https://github.com/functionland/react-native-fula/commit/3254d22373ff9762821db65100e0145b80949272

**Comment by ghorbani-m** [comment]
@ehsan6sha
Right now, the "Reconnect Blox to Wi-Fi" is visible when the device status is "Disconnected", So maybe it is better to add this feature to the settings tab.
What do you think?

**Comment by ehsan6sha** [comment]
done
